language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

dist: xenial

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - test "$TRAVIS_PHP_VERSION" != "nightly" || export COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"

install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --prefer-source $COMPOSER_FLAGS

script:
  - composer validate --strict --no-check-lock
  - composer cscheck
#  - composer phpstan
  - php -d apc.enable_cli=1 vendor/bin/phpunit
#  - vendor/bin/infection
#  - composer clover
#  - composer bccheck
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
